### ISSUE TITLE
NCR could not evaluate the safety of this server

### ISSUE THREAD

**Issue by voidrinix** [Aizistral-Studios/No-Chat-Reports#308] opened 2022-11-30 19:58 UTC
### Modloader

Quilt

### Minecraft Version

1.19.2

### Modloader Version

Quilt Loader 0.18.1-beta.18 + qfapi-4.0.0-beta.22_qsl-3.0.0-beta.22_fapi-0.67.1

### No Chat Reports Version

1.19.2-v1.13.12

### The latest.log File

https://mclo.gs/eUGRDRV

### Bug Description

I just opened the chat and saw a strange icon that said that I need to report a bug

![2022-11-30_22 42 26](https://user-images.githubusercontent.com/73175330/204894801-a882e287-ea7a-408e-a994-6da366e78eeb.png)

### Other Information

NCR installed on server(v1.13.12)
Here is information about my OS 
![изображение](https://user-images.githubusercontent.com/73175330/204895782-cbd3600d-efa4-4ffd-b24c-f09d8729e37a.png)

**Comment by Madis0** [comment] 2022-12-01 05:29
Related or duplicate of #278, though it is unknown how the issue was really resolved there. Is this a Fabric server?

**Comment by voidrinix** [comment] 2022-12-01 07:16
> Related or duplicate of #278, though it is unknown how the issue was really resolved there. Is this a Fabric server?

Yes, server is running on Fabric 0.14.9 + fabric api 0.66.0 , Java 18

**Comment by Madis0** [comment] 2022-12-01 07:19
Seems related to #132 and therefore presumably fixed in 1.19.3 then.

**Comment by Aizistral** [comment] 2022-12-04 10:17
Re-open if persists in 1.19.3.

**Closed as completed by Aizistral** 2022-12-04 10:17 UTC
Labels: bug, confirmed
