### ISSUE TITLE
Make an official No Chat Reports plugin for Bukkit or Spigot servers

### ISSUE THREAD

**Issue by mrjasonn** [Aizistral-Studios/No-Chat-Reports#355] opened 2023-01-26 03:33 UTC
### Idea

Make an official No Chat Reports plugin for Bukkit or Spigot servers developed officially by @Aizistral

### Reasoning

Good to have official plugin by @Aizistral to be compatible with Bukkit and Spigot

**Comment by Madis0** [comment] 2023-01-26 06:13
Fabric, Forge and Bukkit/Spigot platforms are very different, so you can't expect one dev to do all of them. Have a look at https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/Protecting-Server-Players for various options that are already available.

Duplicate of #11

**Closed as not planned by Madis0** 2023-01-26 06:13 UTC
Labels: duplicate, enhancement
