### ISSUE TITLE
Is it possible to make this mod standalone

### ISSUE THREAD

**Issue by xitieshiz2** [Aizistral-Studios/No-Chat-Reports#16] opened 2022-06-24 20:48 UTC
As the title, is it possible to make this mod runs alone without a mod api, just like how optifine works?

**Comment by Aizistral** [comment] 2022-06-24 22:35
Hypothetically - yes. But I do not see how it would provide any advantages. If you can install standalone mod - you might as well install a modloader that will load it as non-standalone, and things are going to be way more compatible that way.

**Comment by JFronny** [comment] 2022-06-25 09:22
A more reasonable approach IMO would be to do something like the iris installer with a modpack containing multiple basic fabric mods, as most people would likely also want things like sodium with it anyways.
In other words, a fork of iris installer with something like Fabulously Optimized (which includes this, btw)

**Comment by dblsaiko** [comment] 2022-06-30 17:10
You can install just Fabric Loader (not Fabric API) and this mod, it will by design not change anything about the vanilla game except the bare minimum necessary to load mods (which isn't anything affecting gameplay) if that's your concern.

**Comment by Aizistral** [comment] 2022-06-30 20:25
> not Fabric API

Actually you have to have that as well. I have to use API for some of the networking.

**Comment by dblsaiko** [comment] 2022-06-30 20:37
Ah, my bad, I didn't actually check if it depended on it and I would have made this without adding any custom networking so I assumed this did the same :^)

**Comment by Aizistral** [comment] 2022-08-09 10:36
If #135 does what it promises to do, then this should be resolved by the fact we will shade necessary parts of Fabric API into NCR.

**Comment by LoganDark** [comment] 2022-08-09 19:38
> If #135 does what it promises to do, then this should be resolved by the fact we will shade necessary parts of Fabric API into NCR.

Yes, that is indeed what it does. Those parts of Fabric API will still be pulled into the game of course, that can't really be avoided.

Note that network API changes client behavior merely by being installed (even if no mods use it) and NCR also tries to advertise itself between server and client so there's no way to escape being modded. In that way NCR is a bit more invasive than it probably could be, but it's an OK tradeoff in terms of developer convenience.

It's very easy to [implement](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/kotlin/net/logandark/veinmine/packet/VeinMinePacketC2S.kt#L26) your [own](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/java/net/logandark/veinmine/mixin/MixinServerPlayNetworkHandler.java#L49) packets, in [both](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/kotlin/net/logandark/veinmine/packet/VeinMinePacketS2C.kt#L26) [directions](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/java/net/logandark/veinmine/mixin/MixinServerPlayNetworkHandler.java#L49), without Fabric API.

**Comment by Aizistral** [comment] 2022-08-14 13:39
> It's very easy to [implement](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/kotlin/net/logandark/veinmine/packet/VeinMinePacketC2S.kt#L26) your [own](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/java/net/logandark/veinmine/mixin/MixinServerPlayNetworkHandler.java#L49) packets, in [both](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/kotlin/net/logandark/veinmine/packet/VeinMinePacketS2C.kt#L26) [directions](https://github.com/LoganDark/fabric-veinmine/blob/3dbe7ce26284ff17e1bdade291e93030ba9d3496/src/main/java/net/logandark/veinmine/mixin/MixinServerPlayNetworkHandler.java#L49), without Fabric API.

Perhaps, but I rely on networking API for things other than packets. For instance - connect and disconnect events. As far as I can tell implementing those on both sides would require around a dozen of new mixins, not to speak of maintenance commitment that dragging them into the mod would create.

**Closed as completed** 2022-08-14 14:46 UTC
Labels: enhancement, confirmed, low priority
