### ISSUE TITLE
Feature Request: Individual encryption keys (and algorithms if possible) for each person in DMs

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [Aizistral-Studios/No-Chat-Reports#256] opened 2022-10-31 19:22 UTC
### Idea

Oh... so I want to see the opportunity to have My own encryption key with each individual person for DMs.
That is, you communicate with one friend in ciphertext on one key, and with another friend - on a completely different one.

### Reasoning

- It can be useful because if you accidently leak your encryption key then you'll leak only you and 1 more person than all friends together.
- More decryption difficulty for "3-rd persons" like from admin dashboard.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment] 2022-10-31 19:35
Actually, #245 has same idea.

**Comment by Madis0** [comment] 2022-11-05 07:11
Duplicate of #245.

**Closed as not planned by Madis0** 2022-11-05 07:11 UTC
Labels: duplicate, enhancement
