### ISSUE TITLE
Let players can decrypt with more keys

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#319] opened 2022-12-07 13:35 UTC
### Idea

I want to let players can set more than 1 keys to decrypt the message, now they can see messages encrypted by different keys if sender use different keys.

### Reasoning

My friends use different keys.

**Comment by Madis0** [comment] 2022-12-07 14:18
How would encrypting work then?

**Comment by IlyaTheSawmill** [comment] 2022-12-08 13:34
You can set more keys in the encryption config, and decrypt all messages with the keys you have set.

**Comment by Madis0** [comment] 2022-12-08 13:45
That's how decryption would work. 

But encryption? Should there be some kind of drop-down for selecting the key to encrypt with?

**Comment by IlyaTheSawmill** [comment] 2022-12-10 02:07
You can select 1 key to encrypt.

**Comment by Aizistral** [comment] 2022-12-12 15:40
Duplicate of #245.

**Closed as not planned by Aizistral** 2022-12-12 15:40 UTC
Labels: duplicate, enhancement
