### ISSUE TITLE
Server status not showing and eventually crashes client

### ISSUE THREAD

**Issue by MacChuck** [Aizistral-Studios/No-Chat-Reports#460] opened 2024-01-12 06:07 UTC
### Modloader

Forge

### Minecraft Version

1.20.1

### Modloader Version

Neoforge 47.1.84

### No Chat Reports Version

1.20.1-v.2.2.2

### Bug Description

Trying to connect to a neoforge server (custom pack) with NoChatReports installed on the client, the server status in the connection list shows pinging, if left long enough the client crashes.

I tried with NoChatReports enabled and disabled on the server, and also tried forcing enablement from the server side in the config.

![image](https://github.com/Aizistral-Studios/No-Chat-Reports/assets/16522925/f2e6f9eb-62d2-48bb-991a-d2f088bef0d2)

Crash report is available here: https://mclo.gs/FyQYJkS

**Comment by shideus** [comment] 2024-03-27 21:52
Same

**Comment by Flintley** [comment] 2024-03-30 19:56
+1

**Comment by eqagunn** [comment] 2024-04-12 23:02
Same issue. No Chat Reports 1.20.1-v.2.2.2 | NeoForge 47.1.84 | FTB Direwolf20 1.12.1

**Comment by P3rf3ctXZer0** [comment] 2024-04-13 12:45
This isn't new https://github.com/Aizistral-Studios/No-Chat-Reports/issues/447

> I found a simple work around if dev is waiting or if they can't fix it. Use Packmenu and set it up so clicking multiplayer goes straight to the server. Or just be faster than 35 secs on screen.

https://github.com/Aizistral-Studios/No-Chat-Reports/issues/447#issuecomment-1951374777

**Comment by Aizistral** [comment] 2024-04-17 09:22
Yeah, looks like a duplicate of #447.

**Closed as not planned by Aizistral** 2024-04-17 09:22 UTC
Labels: bug, duplicate
