### ISSUE TITLE
can up arrow to encryption button

### ISSUE THREAD

**Issue by ManInMyVan** [Aizistral-Studios/No-Chat-Reports#380] opened 2023-03-23 01:24 UTC
### Modloader

Fabric

### Minecraft Version

1.19.4

### Modloader Version

Fabric: Loader 0.14.17 + API 0.76.0

### No Chat Reports Version

1.19.4-v2.1.0

### Bug Description

You can up arrow to the encryption button, preventing the use of up arrowing to a previously sent message.

**Comment by IAmEchino** [comment] 2023-03-23 02:03
PLEASE fix this as soon as possible. It is aggravating beyond words, to the degree that my players are removing this mod for the sole reason of this bug existing (cuz otherwise it's fantastic).

**Comment by Madis0** [comment] 2023-03-23 07:39
Duplicate of #375

**Closed as not planned by Madis0** 2023-03-23 07:39 UTC
Labels: bug
