### ISSUE TITLE
Enhancements about server safety

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#348] opened 2023-01-08 13:10 UTC
### Idea

Some servers don't install No Chat Reports or some other mods or plugins to prevent reporting(even require signs), but in fact, reports cannot occur on these servers, because there are NO player messages at all, all messages are system messages(These server like Hypixel, EarthMC). The security of these servers is "unintrusive" or "insecure".
Can NCR add a function? If there is no player message on the server(all system messages), the server safety will be safe.

### Reasoning

Some servers convert all messages to system messages, but the security of these servers is "unintrusive" or "insecure".

**Comment by Madis0** [comment] 2023-01-08 13:48
Duplicate of #328, related to #177

**Closed as not planned by Madis0** 2023-01-08 13:48 UTC
Labels: enhancement
