### ISSUE TITLE
Encryption broken on paper servers?

### ISSUE THREAD

**Issue by DexrnZacAttack** [Aizistral-Studios/No-Chat-Reports#467] opened 2024-03-10 02:55 UTC
### Modloader

Fabric

### Minecraft Version

1.20.4

### Modloader Version

0.15.7, API version 0.96.4

### No Chat Reports Version

1.20.4-v2.5.0

### Bug Description

Trying to send an encrypted message on a paper server seems to send out garbled data (like reading garbage data in a text editor)
```
[18:43:33] [Render thread/INFO]: [CHAT] <Dexrn> :6%\Â¡(^Â¦$Âª^)$Â¢2Âº<10Â¿
[18:44:02] [Render thread/INFO]: [CHAT] <Dexrn> {+Â±^8~?<'{Â¬Âµ+{Â©Âª@Â².Â«7$^?`{Â±)Â«Â¹;-Â©)\^Â³.%6Â°=~Ã—Â«~@:Â¥]Â°3]Â·Â¿Â¿
[18:44:09] [Render thread/INFO]: [CHAT] <Dexrn> I think the server doesnt like it
```

### Steps to Reproduce

1. Join a paper server on 1.20.4
2. Try to send encrypted messages
3. Observe that the message is all garbled 

### Other Information

We were able to reproduce this with another person.

`[18:41:47] [Render thread/INFO]: [CHAT] <Lucky_C18> ~-%(0Ã—-Â°7Â¥$]Â¦Â®8,Â®=Â©Â¬`

**Comment by anthony1204** [comment] 2024-04-06 04:31
yes, i confirm this is true.

**Comment by Aizistral** [comment] 2024-04-17 09:14
I will look into it

**Comment by anthony1204** [comment] 2024-04-17 09:21
cool.
________________________________

**Comment by Aizistral** [comment] 2024-04-17 09:49
Actually this looks like a duplicate of #454.

**Closed as not planned** 2024-04-17 09:49 UTC
Labels: bug, duplicate, 3rd party issue
