### ISSUE TITLE
Remove version lock from 1.19.2 to 1.19.1

### ISSUE THREAD

**Issue by ghost** [Aizistral-Studios/No-Chat-Reports#181] opened 2022-08-31 16:17 UTC
### Idea

Remove version lock from 1.19.2 to 1.19.1 so that 1.19.1 players can use the latest version of No Chat Reports.

### Reasoning

Removing the version lock allows for players that still play on 1.19.1 (for whatever reason) to use the latest version of No Chat Reports.

### Other Information

Removing the version lock entirely might not be easy, as 1.19.1 and 1.19.2 do have some differences as 1.19.2 "fixes" Gatekeep, as well as more technical changes, but I am sure that it is possible.

**Comment by Aizistral** [comment] 2022-08-31 19:04
Duplicate of #170, implemented in 7df016a51f9251adaece0cf31fd20d35c436442d.

**Closed as completed by Aizistral** 2022-08-31 19:04 UTC
Labels: duplicate, enhancement
